name: build

on:
  push:
    branches: [ master ]
    paths-ignore:
      # Do not run the pipeline if only Markdown files changed
      - '**.md'
jobs:
  test:
    name: Run basic tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test pkg
        run: go test -v ./...

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v ./...
  tag:
    name: Create tag
    needs: test
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a tag
        id: create_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false